sudo: required

language: generic

services:
    - docker

before_install:
    - docker build -t locnguyen1986/docker-complex -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true locnguyen1986/docker-complex npm test -- --coverage

after_success:
    - docker build -t locnguyen1986/docker-complex-client ./client    
    - docker build -t locnguyen1986/docker-complex-nginx ./nginx    
    - docker build -t locnguyen1986/docker-complex-server ./server    
    - docker build -t locnguyen1986/docker-complex-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push locnguyen1986/docker-complex-client
    - docker push locnguyen1986/docker-complex-nginx
    - docker push locnguyen1986/docker-complex-server
    - docker push locnguyen1986/docker-complex-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: 'ap-southeast-1'
    app: 'docker-complex'
    env: 'DockerComplex-env'
    bucket_name: 'elasticbeanstalk-ap-southeast-1-588592860616'
    bucket_path: 'docker-complex'
    on:
        branch: master    
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
